dict={}
name=input("Enter name : ")
language=input("Enter your favourite language : ")
dict.update({name:language})
name=input("Enter name : ")
language=input("Enter your favourite language : ")
dict.update({name:language})
name=input("Enter name : ")
language=input("Enter your favourite language : ")
dict.update({name:language})
name=input("Enter name : ")
language=input("Enter your favourite language : ")
dict.update({name:language})
print(dict)